using System.Text.Json.Serialization;

namespace AiTestAgent.src;

/// <summary>
/// Represents a single step in a test plan generated by the AI.
/// </summary>
public class TestStep
{
    [JsonPropertyName("step")]
    public int Step { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    // The ID, name, or selector of the UI element to interact with.
    [JsonPropertyName("element")]
    public string? Element { get; set; }

    // The action to perform (e.g., "navigate", "type", "click"...).
    [JsonPropertyName("action")]
    public string Action { get; set; } = string.Empty;

    // The value to use with the action (e.g., text to type, URL to navigate to).
    [JsonPropertyName("value")]
    public string? Value { get; set; }
}

/// <summary>
/// Represents the complete test plan, containing a list of test steps.
/// </summary>
public class TestPlan
{
    [JsonPropertyName("test_plan")]
    public List<TestStep> Steps { get; set; } = new();
}
